In [1]:
import numpy as np
import random
import gensim
from nltk.corpus import words
from functools import reduce
import heapq
import os
import collections

In [203]:
wrds = np.genfromtxt('words.txt', delimiter=',', dtype=str).tolist()

ValueError: Some errors were detected !
    Line #10 (got 400 columns instead of 1)

In [30]:
words_upper = ["Hollywood", "Well", "Foot", "New York", "Spring", "Court", "Tube", "Point", "Tablet", "Slip", "Date", "Drill", "Lemon", "Bell", "Screen", "Fair", "Torch", "State", "Match", "Iron", "Block", "France", "Australia", "Limousine", "Stream", "Glove", "Nurse", "Leprechaun", "Play", "Tooth", "Arm", "Bermuda", "Diamond", "Whale", "Comic", "Mammoth", "Green", "Pass", "Missile", "Paste", "Drop", "Pheonix", "Marble", "Staff", "Figure", "Park", "Centaur", "Shadow", "Fish", "Cotton", "Egypt", "Theater", "Scale", "Fall", "Track", "Force", "Dinosaur", "Bill", "Mine", "Turkey", "March", "Contract", "Bridge", "Robin", "Line", "Plate", "Band", "Fire", "Bank", "Boom", "Cat", "Shot", "Suit", "Chocolate", "Roulette", "Mercury", "Moon", "Net", "Lawyer", "Satellite", "Angel", "Spider", "Germany", "Fork", "Pitch", "King", "Crane", "Trip", "Dog", "Conductor", "Part", "Bugle", "Witch", "Ketchup", "Press", "Spine", "Worm", "Alps", "Bond", "Pan", "Beijing", "Racket", "Cross", "Seal", "Aztec", "Maple", "Parachute", "Hotel", "Berry", "Soldier", "Ray", "Post", "Greece", "Square", "Mass", "Bat", "Wave", "Car", "Smuggler", "England", "Crash", "Tail", "Card", "Horn", "Capital", "Fence", "Deck", "Buffalo", "Microscope", "Jet", "Duck", "Ring", "Train", "Field", "Gold", "Tick", "Check", "Queen", "Strike", "Kangaroo", "Spike", "Scientist", "Engine", "Shakespeare", "Wind", "Kid", "Embassy", "Robot", "Note", "Ground", "Draft", "Ham", "War", "Mouse", "Center", "China", "Bolt", "Spot", "Piano", "Pupil", "Plot", "Lion", "Police", "Head", "Litter", "Concert", "Mug", "Vacuum", "Atlantis", "Straw", "Switch", "Skyscraper", "Laser", "Scuba Diver", "Africa", "Plastic", "Dwarf", "Lap", "Life", "Honey", "Horseshoe", "Unicorn", "Spy", "Pants", "Wall", "Paper", "Sound", "Ice", "Tag", "Web", "Fan", "Orange", "Temple", "Canada", "Scorpion", "Undertaker", "Mail", "Europe", "Soul", "Apple", "Pole", "Tap", "Mouth", "Ambulance", "Dress", "IceCream", "Rabbit", "Buck", "Agent", "Sock", "Nut", "Boot", "Ghost", "Oil", "Superhero", "Code", "Kiwi", "Hospital", "Saturn", "Film", "Button", "Snowman", "Helicopter", "Log", "Princess", "Time", "Cook", "Revolution", "Shoe", "Mole", "Spell", "Grass", "Washer", "Game", "Beat", "Hole", "Horse", "Pirate", "Link", "Dance", "Fly", "Pit", "Server", "School", "Lock", "Brush", "Pool", "Star", "Jam", "Organ", "Berlin", "Face", "Luck", "Amazon", "Cast", "Gas", "Club", "Sink", "Water", "Chair", "Shark", "Jupiter", "Copper", "Jack", "Platypus", "Stick", "Olive", "Grace", "Bear", "Glass", "Row", "Pistol", "London", "Rock", "Van", "Vet", "Beach", "Charge", "Port", "Disease", "Palm", "Moscow", "Pin", "Washington", "Pyramid", "Opera", "Casino", "Pilot", "String", "Night", "Chest", "Yard", "Teacher", "Pumpkin", "Thief", "Bark", "Bug", "Mint", "Cycle", "Telescope", "Calf", "Air", "Box", "Mount", "Thumb", "Antarctica", "Trunk", "Snow", "Penguin", "Root", "Bar", "File", "Hawk", "Battery", "Compound", "Slug", "Octopus", "Whip", "America", "Ivory", "Pound", "Sub", "Cliff", "Lab", "Eagle", "Genius", "Ship", "Dice", "Hood", "Heart", "Novel", "Pipe", "Himalayas", "Crown", "Round", "India", "Needle", "Shop", "Watch", "Lead", "Tie", "Table", "Cell", "Cover", "Czech", "Back", "Bomb", "Ruler", "Forest", "Bottle", "Space", "Hook", "Doctor", "Ball", "Bow", "Degree", "Rome", "Plane", "Giant", "Nail", "Dragon", "Stadium", "Flute", "Carrot", "Wake", "Fighter", "Model", "Tokyo", "Eye", "Mexico", "Hand", "Swing", "Key", "Alien", "Tower", "Poison", "Cricket", "Cold", "Knife", "Church", "Board", "Cloak", "Ninja", "Olympus", "Belt", "Light", "Death", "Stock", "Millionaire", "Day", "Knight", "Pie", "Bed", "Circle", "Rose", "Change", "Cap", "Triangle", "Chick"]

words = [x.lower() for x in words_upper]
print words

['hollywood', 'well', 'foot', 'new york', 'spring', 'court', 'tube', 'point', 'tablet', 'slip', 'date', 'drill', 'lemon', 'bell', 'screen', 'fair', 'torch', 'state', 'match', 'iron', 'block', 'france', 'australia', 'limousine', 'stream', 'glove', 'nurse', 'leprechaun', 'play', 'tooth', 'arm', 'bermuda', 'diamond', 'whale', 'comic', 'mammoth', 'green', 'pass', 'missile', 'paste', 'drop', 'pheonix', 'marble', 'staff', 'figure', 'park', 'centaur', 'shadow', 'fish', 'cotton', 'egypt', 'theater', 'scale', 'fall', 'track', 'force', 'dinosaur', 'bill', 'mine', 'turkey', 'march', 'contract', 'bridge', 'robin', 'line', 'plate', 'band', 'fire', 'bank', 'boom', 'cat', 'shot', 'suit', 'chocolate', 'roulette', 'mercury', 'moon', 'net', 'lawyer', 'satellite', 'angel', 'spider', 'germany', 'fork', 'pitch', 'king', 'crane', 'trip', 'dog', 'conductor', 'part', 'bugle', 'witch', 'ketchup', 'press', 'spine', 'worm', 'alps', 'bond', 'pan', 'beijing', 'racket', 'cross', 'seal', 'aztec', 'maple', 'parachute

In [31]:
board = random.sample(words, 25)

player1 = board[:9]
player2 = board[9:17]
neutral = board[17:24]
assassin = board[24]

print player1, player2, neutral, assassin

['track', 'park', 'parachute', 'knife', 'cell', 'table', 'bridge', 'olive', 'yard'] ['gold', 'boot', 'spine', 'horseshoe', 'undertaker', 'point', 'comic', 'cast'] ['pole', 'scale', 'bed', 'change', 'pie', 'cook', 'revolution'] death


In [32]:
positives = model[player1]
print positives

[[-0.013537  -0.028098   0.045745  ... -0.20906    0.051424   0.041097 ]
 [ 0.035629   0.19435   -0.46777   ...  0.38785    0.45448    0.38366  ]
 [ 0.048651  -0.36089    0.19444   ... -0.23537   -0.074001  -0.23663  ]
 ...
 [-0.028964  -0.76821    0.014601  ...  0.15432    0.076667   0.47699  ]
 [-0.31707    0.27897    0.13695   ... -0.32028    0.12964    0.069003 ]
 [-0.22935    0.12795   -0.30681   ... -0.10339    0.0040666  0.13925  ]]


In [4]:
model = gensim.models.KeyedVectors.load_word2vec_format('glove.6B.300d.w2vformat.txt', binary=False)

In [164]:
from nltk.cluster import KMeansClusterer
import nltk

In [165]:
NUM_CLUSTERS=3

kclusterer1 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.cosine_distance, repeats=25)
assigned_clusters1 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer2 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.cosine_distance, repeats=25)
# assigned_clusters2 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer3 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.cosine_distance, repeats=25)
# assigned_clusters3 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer4 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.cosine_distance, repeats=25)
# assigned_clusters4 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer5 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.cosine_distance, repeats=25)
# assigned_clusters5 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer6 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
# assigned_clusters6 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer7 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
# assigned_clusters7 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer8 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
# assigned_clusters8 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer9 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
# assigned_clusters9 = kclusterer.cluster(positives, assign_clusters=True)

# kclusterer10 = KMeansClusterer(NUM_CLUSTERS, distance=nltk.cluster.util.euclidean_distance, repeats=25)
# assigned_clusters10 = kclusterer.cluster(positives, assign_clusters=True)

print (assigned_clusters1)

Error: no centroid defined for empty cluster.
Try setting argument 'avoid_empty_clusters' to True


AssertionError: 

In [53]:
wordsDict = collections.defaultdict()
cluster_iteration = [assigned_clusters1, assigned_clusters2, assigned_clusters3, assigned_clusters4, assigned_clusters5, assigned_clusters6, assigned_clusters7, assigned_clusters8, assigned_clusters9, assigned_clusters10]

In [58]:
for i in range(9):
    for j in range(9):
        if i < j:
        # same word
            if i != j:
                for iteration in cluster_iteration:
                    if iteration[i] == iteration[j]:
                        wordsDict[(i,j)] += 1

In [59]:
print wordsDict

defaultdict(None, {(1, 2): 2, (7, 8): 6, (2, 5): 2, (2, 6): 5, (6, 7): 2, (4, 6): 6, (5, 6): 5, (2, 8): 3, (1, 4): 2, (2, 4): 8, (0, 6): 2, (3, 6): 2, (0, 4): 6, (0, 3): 2, (6, 8): 3, (0, 2): 3, (5, 8): 3, (3, 5): 7})


In [5]:
from sklearn.cluster import KMeans
from sklearn import metrics

In [115]:
print player1

['bill', 'spy', 'berlin', 'buffalo', 'king', 'flute', 'mount', 'center', 'bond']


In [33]:
# https://stackoverflow.com/questions/40828929/sklearn-mean-distance-from-centroid-of-each-cluster

kmeans1 = KMeans(n_clusters=5)
clusters1 = kmeans1.fit_predict(positives)
centroids1 = kmeans1.cluster_centers_

mean_distances1 = {}
mean_count1 = {}

kmeans2 = KMeans(n_clusters=4)
clusters2 = kmeans2.fit_predict(positives)
centroids2 = kmeans2.cluster_centers_

mean_distances2 = {}
mean_count2 = {}

kmeans3 = KMeans(n_clusters=4)
clusters3 = kmeans3.fit_predict(positives)
centroids3 = kmeans3.cluster_centers_

mean_distances3 = {}
mean_count3 = {}

for i in range(5):
    mean_distances1[i] = 0
    mean_count1[i] = 0

for i in range(4):
    mean_distances2[i] = 0
    mean_count2[i] = 0

for i in range(4):
    mean_distances3[i] = 0
    mean_count3[i] = 0

# go through clusters and calculate distance to centroid for each
for i in range(9):
    cluster1 = clusters1[i]
    centroid1 = centroids1[cluster1]
    distance1 = np.linalg.norm(centroid1-positives[i])
    mean_distances1[cluster1] += distance1
    mean_count1[cluster1] += 1
    
    cluster2 = clusters2[i]
    centroid2 = centroids2[cluster2]
    distance2 = np.linalg.norm(centroid2-positives[i])
    mean_distances2[cluster2] += distance2
    mean_count2[cluster2] += 1
    
    cluster3 = clusters3[i]
    centroid3 = centroids3[cluster3]
    distance3 = np.linalg.norm(centroid3-positives[i])
    mean_distances3[cluster3] += distance3
    mean_count3[cluster3] += 1

mean_cluster1 = []
mean_cluster2 = []
mean_cluster3 = []

# calculate mean
for i in range(5):
    mean_cluster1.append(mean_distances1[i]/mean_count1[i])
    
for i in range(4):
    mean_cluster2.append(mean_distances2[i]/mean_count2[i])
    
for i in range(4):
    mean_cluster3.append(mean_distances3[i]/mean_count3[i])
    
print mean_cluster1
print mean_distances1
print mean_count1

print mean_cluster2
print mean_distances2
print mean_count2

print mean_cluster3
print mean_distances3
print mean_count3

[2.0987985749343352e-07, 4.984995126724243, 1.4994384400779381e-07, 4.196436882019043, 1.7972598698179354e-07]
{0: 2.0987985749343352e-07, 1: 19.939980506896973, 2: 1.4994384400779381e-07, 3: 8.392873764038086, 4: 1.7972598698179354e-07}
{0: 1, 1: 4, 2: 1, 3: 2, 4: 1}
[5.0188751220703125, 4.984995126724243, 2.0987985749343352e-07, 1.7972598698179354e-07]
{0: 15.056625366210938, 1: 19.939980506896973, 2: 2.0987985749343352e-07, 3: 1.7972598698179354e-07}
{0: 3, 1: 4, 2: 1, 3: 1}
[1.7972598698179354e-07, 4.984995126724243, 5.0188751220703125, 2.0987985749343352e-07]
{0: 1.7972598698179354e-07, 1: 19.939980506896973, 2: 15.056625366210938, 3: 2.0987985749343352e-07}
{0: 1, 1: 4, 2: 3, 3: 1}


In [34]:
print clusters1
print clusters2
print clusters3
print player1

[1 1 0 3 4 3 1 2 1]
[1 1 2 0 3 0 1 0 1]
[1 1 3 2 0 2 1 2 1]
['track', 'park', 'parachute', 'knife', 'cell', 'table', 'bridge', 'olive', 'yard']


In [ ]:
# todo: hyperparameter for tightness of cluster vs number of clues
# for now, using tights cluster with largest number of words

In [35]:
# finding tightest cluster

minimum_value = 10
words = []

for index, value in enumerate(mean_cluster1):
    if mean_count1[index] > 1 and value < minimum_value:
        minimum_value = value
        indices = [i for i, e in enumerate(clusters1) if e == index]
        temp_words = []
        for i in indices:
            temp_words.append(player1[i])
        words = temp_words
        
for index, value in enumerate(mean_cluster2):
    if mean_count2[index] > 1 and value < minimum_value:
        minimum_value = value
        indices = [i for i, e in enumerate(clusters2) if e == index]
        temp_words = []
        for i in indices:
            temp_words.append(player1[i])
        words = temp_words
        
for index, value in enumerate(mean_cluster3):
    if mean_count3[index] > 1 and value < minimum_value:
        minimum_value = value
        indices = [i for i, e in enumerate(clusters3) if e == index]
        temp_words = []
        for i in indices:
            temp_words.append(player1[i])
        words = temp_words
        
print words

['knife', 'table']


In [36]:
# other choice: find largest count

combined = [0, clusters1, clusters2, clusters3]

largest_count = 0
count_value = 0
count_index = 0
trial = 0

for index in range(5):
    if mean_count1[index] > largest_count:
        largest_count = mean_count1[index]
        count_value = mean_cluster1[index]
        count_index = index
        trial = 1
    if mean_count1[index] == largest_count:
        if mean_cluster1[index] < count_value:
            count_index = index
            count_value = mean_cluster1[index]
            trial = 1
        
for index in range(4):
    if mean_count2[index] > largest_count:
        largest_count = mean_count2[index]
        count_value = mean_cluster2[index]
        count_index = index
        trial = 2
    if mean_count2[index] == largest_count:
        if mean_cluster2[index] < count_value:
            count_index = index
            count_value = mean_cluster2[index]
            trial = 2
            
    if mean_count3[index] > largest_count:
        largest_count = mean_count3[index]
        count_value = mean_cluster3[index]
        count_index = index
        trial = 3
    if mean_count3[index] == largest_count:
        if mean_cluster3[index] < count_value:
            count_index = index
            count_value = mean_cluster3[index]
            trial = 3

print largest_count
print count_value
print count_index
print trial

words = []
print combined[trial]
indices = [i for i, e in enumerate(combined[trial]) if e == count_index]
for i in indices:
    words.append(player1[i])
    
print words

4
4.984995126724243
1
1
[1 1 0 3 4 3 1 2 1]
['track', 'park', 'bridge', 'yard']


In [48]:
full_hint = model.most_similar(
    positive=words,
    negative=player2 + [assassin],
    restrict_vocab=50000
)

hint = full_hint[0][0]
print hint

right-of-way


In [305]:
print board

['queen', 'figure', 'tap', 'worm', 'night', 'park', 'fall', 'bell', 'olive', 'jet', 'turkey', 'tablet', 'shot', 'wake', 'limousine', 'note', 'button', 'ball', 'date', 'bolt', 'luck', 'berry', 'root', 'robin', 'giant']


In [40]:
guesser = model[board]
print guesser

[[-0.013537 -0.028098  0.045745 ... -0.20906   0.051424  0.041097]
 [ 0.035629  0.19435  -0.46777  ...  0.38785   0.45448   0.38366 ]
 [ 0.048651 -0.36089   0.19444  ... -0.23537  -0.074001 -0.23663 ]
 ...
 [ 0.37224  -0.34577   0.35999  ... -0.091241 -0.62353   0.24756 ]
 [ 0.45979  -0.22301   0.18176  ... -0.21289   0.034345 -0.2813  ]
 [-0.095281  0.19231   0.35916  ...  0.3247   -0.17704   0.29431 ]]


In [49]:
model.most_similar(
    positive=hint,
    restrict_vocab=50000
)

[(u'roadway', 0.5434665083885193),
 (u'four-lane', 0.5191274285316467),
 (u'paralleling', 0.5083836913108826),
 (u'railroad', 0.5073590278625488),
 (u'two-lane', 0.5033497214317322),
 (u'terminus', 0.49456170201301575),
 (u'streetcar', 0.4910515546798706),
 (u'csx', 0.46943289041519165),
 (u'footpath', 0.45075321197509766),
 (u'alignment', 0.44879063963890076)]

In [50]:
guesser_model = model[board]
print guesser_model

[[-0.013537 -0.028098  0.045745 ... -0.20906   0.051424  0.041097]
 [ 0.035629  0.19435  -0.46777  ...  0.38785   0.45448   0.38366 ]
 [ 0.048651 -0.36089   0.19444  ... -0.23537  -0.074001 -0.23663 ]
 ...
 [ 0.37224  -0.34577   0.35999  ... -0.091241 -0.62353   0.24756 ]
 [ 0.45979  -0.22301   0.18176  ... -0.21289   0.034345 -0.2813  ]
 [-0.095281  0.19231   0.35916  ...  0.3247   -0.17704   0.29431 ]]


In [59]:
similarities = []
for word in board:
    prob = model.similarity(hint, word)
    similarities.append((word, prob))

print similarities

[('track', 0.22234301), ('park', 0.16816987), ('parachute', -0.05921454), ('knife', 0.014912669), ('cell', -0.058619652), ('table', -0.07265681), ('bridge', 0.24698782), ('olive', 0.06442585), ('yard', 0.21688974), ('gold', -0.030817654), ('boot', -0.12772027), ('spine', -0.04533045), ('horseshoe', 0.05728756), ('undertaker', -0.009304337), ('point', 0.014696382), ('comic', -0.098254554), ('cast', -0.1071277), ('pole', 0.06081599), ('scale', -0.0070951656), ('bed', 0.029621579), ('change', -0.07725541), ('pie', -0.052529875), ('cook', -0.10230957), ('revolution', -0.097287275), ('death', -0.085452996)]


In [54]:
from gensim.similarities.index import AnnoyIndexer
from gensim.models import Word2Vec

guesser_model = Word2Vec(board, min_count=1, seed=1)

indexer = AnnoyIndexer(model, 4)
guesser_model.most_similar(hint, topn=4, indexer=indexer)

ImportError: Annoy has not been installed, if you wish to use the annoy indexer, please run `pip install annoy`

In [51]:
guesser = gensim.models.KeyedVectors.load_word2vec_format(guesser_model, binary=False)

TypeError: don't know how to handle uri array([[-0.013537, -0.028098,  0.045745, ..., -0.20906 ,  0.051424,
         0.041097],
       [ 0.035629,  0.19435 , -0.46777 , ...,  0.38785 ,  0.45448 ,
         0.38366 ],
       [ 0.048651, -0.36089 ,  0.19444 , ..., -0.23537 , -0.074001,
        -0.23663 ],
       ...,
       [ 0.37224 , -0.34577 ,  0.35999 , ..., -0.091241, -0.62353 ,
         0.24756 ],
       [ 0.45979 , -0.22301 ,  0.18176 , ..., -0.21289 ,  0.034345,
        -0.2813  ],
       [-0.095281,  0.19231 ,  0.35916 , ...,  0.3247  , -0.17704 ,
         0.29431 ]], dtype=float32)